export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="jreese"
plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH=$HOME/bin:/usr/local/bin:$PATH
export SSH_KEY_PATH="~/.ssh/dsa_id"

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
